Repository ankitpokhrel/jira-cli, pull requests merged in 2021-09, with the labels that each got.

#137 Update browser module - Adds NetBSD support.
  go.mod
  go.sum
Labels: dependency

#136 feat: Support init cmd for on-premise jira installation
  README.md
  internal/config/generator.go
  pkg/jira/createmeta.go
  pkg/jira/createmeta_test.go
  pkg/jira/me.go
  pkg/jira/me_test.go
  pkg/jira/project.go
  pkg/jira/project_test.go
Labels: feature

#139 feat: Support clone cmd for on-premise jira installation
  api/client.go
  internal/cmd/issue/clone/clone.go
  internal/config/generator.go
  pkg/jira/client.go
  pkg/jira/issue.go
  pkg/jira/issue_test.go
Labels: feature

#141 feat: Support link cmd for on-premise jira installation
  pkg/jira/issue.go
  pkg/jira/issue_test.go
Labels: feature

#147 feat: Support move cmd for on-premise jira installation
  api/client.go
  internal/cmd/issue/move/move.go
  pkg/jira/transition.go
  pkg/jira/transition_test.go
Labels: feature, jira server

#148 feat: Basic support for view command for on-premise jira installation
  internal/cmd/issue/view/view.go
  internal/view/issue.go
  internal/view/issue_test.go
  pkg/jira/issue.go
Labels: feature, jira server

#149 feat: Support interactive view mode for on-premise jira installation
  internal/cmd/sprint/list/list.go
  internal/view/epic.go
  internal/view/issues.go
  internal/view/sprint.go
Labels: feature, jira server

#150 feat: Support edit cmd for on-premise jira installation
  internal/cmd/issue/edit/edit.go
Labels: feature, jira server
